### ISSUE TITLE
ToneJS types out of sync

### ISSUE THREAD

**Issue by panmichal** [MusicAsCode/set-player#3]
I noticed that type definitions from `https://github.com/Tonejs/TypeScript.git` are used.
According to https://github.com/Tonejs/Tone.js/wiki/Typescripting-Tone.js `typescript` branch in the library repo should be used instead. 
The former doesn't seem to be maintained - last commit in November

**Comment by styk-tv** [comment]
OK solved with the dependencies. I tagged working version as v0.2. Will add details to PR#4
